import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./globals.css";
import Providers from '@/components/providers';
import Navbar from "@/components/navbar";
import Footer from '@/components/footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Define the RootLayout function 


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Providers>
        <div className='flex flex-col min-h-screen'>
          <Navbar />
            {children}
            <div className='grow' />
            <Footer />       
             </div>
      </Providers>
    </html>
  )
}
